package org.land.skycraftclient.client.packet;

public enum EnumMessageType {
    DODGE, DODGE_SUCCESS, DODGE_FAILED, NORMAL_SWORD_ATTACK, DOUBLE_SWORD_ATTACK,
    SPEAR_ATTACK, SHIELD_STOP, DOUBLE_EDGED_ATTACK, BOW, TWO_HANDED_SWORD, BOW_SHOOT
    , WAND, SHIELD_LEFT, SHIELD_RIGHT, JUMP, JUMP_WALK_LEFT, JUMP_WALK_RIGHT, WALK, JUMP_RUN_LEFT, JUMP_RUN_RIGHT
}
